name: "Custom GitHub Action"
description: "A GitHub Action that takes an input and returns the square of the number"

inputs:
  code-language:
    description: "Enter a code language:[python, php]"
    required: true
    default: "python"
  language:
    description: "Enter a language[zh-TW, zh-CN]"
    required: true
    default: "zh-TW"
outputs:
  code-language:
    description: "The code language"
  language:
    description: "The language"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install necessary packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install opencc

    - name: Show Python version
      shell: bash
      run: echo "::notify::`python -V`"

    - name: Show Python packages
      shell: bash
      run: |
        echo "::group::Python Packages"
        echo "`pip list`"
        echo "::endgroup::"

    - name: Run Check
      shell: bash
      run: |
        echo "::group::Run Check"
        python main.py
        echo "::endgroup::"
